"""add_assistant_and_sync_schema

Revision ID: 6b3a6fb5d5b3
Revises: 8638d8e3e513
Create Date: 2026-06-12 14:57:39.789503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3a6fb5d5b3'
down_revision: Union[str, Sequence[str], None] = '8638d8e3e513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('educational_articles', sa.Column('slug', sa.String(length=255), server_default='', nullable=False))
    op.add_column('educational_articles', sa.Column('summary', sa.String(length=1000), server_default='', nullable=False))
    op.add_column('educational_articles', sa.Column('crop_tags', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('educational_articles', sa.Column('media_url', sa.String(length=500), nullable=True))
    op.add_column('educational_articles', sa.Column('language', sa.String(length=10), server_default='en', nullable=False))
    op.add_column('educational_articles', sa.Column('status', sa.String(length=20), server_default='draft', nullable=False))
    op.create_index(op.f('ix_educational_articles_slug'), 'educational_articles', ['slug'], unique=True)
    op.add_column('farmer_profiles', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('farmer_profiles', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('farmer_profiles', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('farmer_profiles', sa.Column('location_visibility', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('farmer_profiles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('crop_listings', sa.Column('status', sa.String(length=50), server_default='active', nullable=False))
    op.add_column('crop_listings', sa.Column('category', sa.String(length=100), server_default='Vegetables', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop_listings', 'category')
    op.drop_column('crop_listings', 'status')
    op.drop_column('farmer_profiles', 'updated_at')
    op.drop_column('farmer_profiles', 'location_visibility')
    op.drop_column('farmer_profiles', 'state')
    op.drop_column('farmer_profiles', 'city')
    op.drop_column('farmer_profiles', 'district')
    op.drop_index(op.f('ix_educational_articles_slug'), table_name='educational_articles')
    op.drop_column('educational_articles', 'status')
    op.drop_column('educational_articles', 'language')
    op.drop_column('educational_articles', 'media_url')
    op.drop_column('educational_articles', 'crop_tags')
    op.drop_column('educational_articles', 'summary')
    op.drop_column('educational_articles', 'slug')
    op.drop_table('assistant_messages')
    op.drop_table('assistant_conversations')
    # ### end Alembic commands ###
